const color = {
  RED: '160',
  DRED: '124',
  YELLOW: '226',
  GREEN: '34',
  DGREEN: '28',
  BLUE: '21',
  DBLUE: '18',
  FIRE: '196',
  ORANGE: '208',
  AZURE: '33',
  LIME: '148',
  PINK: '199',
  PLUM: '93',
  TURQ: '39',
  ORED: '202',
  GREY: '247',
  DGREY: '244',
  DDGREY: '241',
  LGREY: '250',
  LLGREY: '254',
  LBROWN: '173',
  BROWN: '130',
  BLACK: '0',
  WHITE: '15'
}

module.exports = color
module.exports.colorMethods = [
  { name: 'red', color: color.RED, fgcolor: color.BLACK },
  { name: 'dred', color: color.DRED, fgcolor: color.WHITE },
  { name: 'yellow', color: color.YELLOW, fgcolor: color.BLACK },
  { name: 'green', color: color.GREEN, fgcolor: color.BLACK },
  { name: 'dgreen', color: color.DGREEN, fgcolor: color.WHITE },
  { name: 'blue', color: color.BLUE, fgcolor: color.WHITE },
  { name: 'dblue', color: color.DBLUE, fgcolor: color.WHITE },
  { name: 'fire', color: color.FIRE, fgcolor: color.BLACK },
  { name: 'orange', color: color.ORANGE, fgcolor: color.BLACK },
  { name: 'azure', color: color.AZURE, fgcolor: color.BLACK },
  { name: 'lime', color: color.LIME, fgcolor: color.BLACK },
  { name: 'pink', color: color.PINK, fgcolor: color.BLACK },
  { name: 'plum', color: color.PLUM, fgcolor: color.WHITE },
  { name: 'turq', color: color.TURQ, fgcolor: color.BLACK },
  { name: 'ored', color: color.ORED, fgcolor: color.BLACK },
  { name: 'grey', color: color.GREY, fgcolor: color.BLACK },
  { name: 'dgrey', color: color.DGREY, fgcolor: color.BLACK },
  { name: 'ddgrey', color: color.DDGREY, fgcolor: color.WHITE },
  { name: 'lgrey', color: color.LGREY, fgcolor: color.BLACK },
  { name: 'llgrey', color: color.LLGREY, fgcolor: color.BLACK },
  { name: 'lbrown', color: color.LBROWN, fgcolor: color.BLACK },
  { name: 'brown', color: color.BROWN, fgcolor: color.BLACK },
  { name: 'black', color: color.BLACK, fgcolor: color.WHITE },
  { name: 'white', color: color.WHITE, fgcolor: color.BLACK }
]
